version: '2.4'
services:
    rsu:
        hostname: rsu
        image: vanetza:lane_merge
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=99
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - SUPPORT_MAC_BLOCKING=true
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_LATITUDE=41.704018
            - VANETZA_LONGITUDE=-8.798036
            - VANETZA_BEACONS_ENABLED=false
            - VANETZA_CPM_ENABLED=false
            - VANETZA_VAM_ENABLED=false
            - VANETZA_SPATEM_ENABLED=false
            - VANETZA_MAPEM_ENABLED=false
            - VANETZA_CAM_DDS_ENABLED=false
            - VANETZA_DENM_DDS_ENABLED=false
            - VANETZA_CPM_DDS_ENABLED=false
            - VANETZA_VAM_DDS_ENABLED=false
            - VANETZA_SPATEM_DDS_ENABLED=false
            - VANETZA_MAPEM_DDS_ENABLED=false
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.254
        sysctls:      
            kernel.msgmax:  16384

    car_1:
        hostname: car_1
        image: vanetza:lane_merge
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - SUPPORT_MAC_BLOCKING=true
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_BEACONS_ENABLED=false
            - VANETZA_CPM_ENABLED=false
            - VANETZA_VAM_ENABLED=false
            - VANETZA_SPATEM_ENABLED=false
            - VANETZA_MAPEM_ENABLED=false
            - VANETZA_CAM_DDS_ENABLED=false
            - VANETZA_DENM_DDS_ENABLED=false
            - VANETZA_CPM_DDS_ENABLED=false
            - VANETZA_VAM_DDS_ENABLED=false
            - VANETZA_SPATEM_DDS_ENABLED=false
            - VANETZA_MAPEM_DDS_ENABLED=false
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  16384

    car_2:
        hostname: car_2
        image: vanetza:lane_merge
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=br0
            - SUPPORT_MAC_BLOCKING=true
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_BEACONS_ENABLED=false
            - VANETZA_CPM_ENABLED=false
            - VANETZA_VAM_ENABLED=false
            - VANETZA_SPATEM_ENABLED=false
            - VANETZA_MAPEM_ENABLED=false
            - VANETZA_CAM_DDS_ENABLED=false
            - VANETZA_DENM_DDS_ENABLED=false
            - VANETZA_CPM_DDS_ENABLED=false
            - VANETZA_VAM_DDS_ENABLED=false
            - VANETZA_SPATEM_DDS_ENABLED=false
            - VANETZA_MAPEM_DDS_ENABLED=false
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.11
        sysctls:      
            kernel.msgmax:  16384

    car_3:
        hostname: car_3
        image: vanetza:lane_merge
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:04
            - VANETZA_INTERFACE=br0
            - SUPPORT_MAC_BLOCKING=true
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_BEACONS_ENABLED=false
            - VANETZA_CPM_ENABLED=false
            - VANETZA_VAM_ENABLED=false
            - VANETZA_SPATEM_ENABLED=false
            - VANETZA_MAPEM_ENABLED=false
            - VANETZA_CAM_DDS_ENABLED=false
            - VANETZA_DENM_DDS_ENABLED=false
            - VANETZA_CPM_DDS_ENABLED=false
            - VANETZA_VAM_DDS_ENABLED=false
            - VANETZA_SPATEM_DDS_ENABLED=false
            - VANETZA_MAPEM_DDS_ENABLED=false
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.12
        sysctls:      
            kernel.msgmax:  16384
    car_merge:
        hostname: car_merge
        image: vanetza:lane_merge
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:05
            - VANETZA_INTERFACE=br0
            - SUPPORT_MAC_BLOCKING=true
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_BEACONS_ENABLED=false
            - VANETZA_CPM_ENABLED=false
            - VANETZA_VAM_ENABLED=false
            - VANETZA_SPATEM_ENABLED=false
            - VANETZA_MAPEM_ENABLED=false
            - VANETZA_CAM_DDS_ENABLED=false
            - VANETZA_DENM_DDS_ENABLED=false
            - VANETZA_CPM_DDS_ENABLED=false
            - VANETZA_VAM_DDS_ENABLED=false
            - VANETZA_SPATEM_DDS_ENABLED=false
            - VANETZA_MAPEM_DDS_ENABLED=false
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.13
        sysctls:      
            kernel.msgmax:  16384
            
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0
